import argparse
import dataclasses
from typing import Optional
from langchain_core.language_models import BaseChatModel
from youtube_transcript_api import YouTubeTranscriptApi, FetchedTranscript
import re, json
from pathlib import Path
from yt_dlp import YoutubeDL
import dotenv
from datetime import datetime
from pathvalidate import sanitize_filename


dotenv.load_dotenv()
__MODEL : Optional[BaseChatModel] = None

SYSTEM_PROMPT ="""
You are an expert summarizer specializing in extracting key insights from spoken content such as lectures, interviews, and documentaries.
Your goal is to produce informative, concise, and accurate summaries from raw YouTube transcripts.

Instructions:
1. Comprehension: Read the entire transcript carefully to understand the main topic, structure, and arguments.
2. Summarization:
    - Capture the main ideas, key arguments, and important details.
    - Preserve factual accuracy and the speaker’s intent.
    - Avoid filler words, introductions, or repetition.
3. Style:
    - Write in clear, objective, and neutral tone.
    - Use short paragraphs or bullet points if appropriate.
    - Make it informative, not just brief — focus on what was said and why it matters.
4. Output:
    - Produce a 1–3 paragraph summary (or longer for very detailed videos).
    - Optionally include a short list of key takeaways if helpful.

Example Output:
### Summary
[Concise yet detailed summary of the transcript’s main ideas.]

### Key Takeaways
- [Main point 1]: [Explanation]
- [Main point 2]
    [Detailed explanation if needed]
- [Main point 3]
"""


@dataclasses.dataclass
class Config:
    url: str
    file: Optional[str] = None
    use_custom_prompt: bool = False
    custom_prompt_file: Optional[str] = None
    output_dir: str = "outputs"
    model: str = "gpt-3.5-turbo"
    model_provider: str = "openai"
    model_kwargs: dict = dataclasses.field(default_factory=dict)

def get_video_id(url) -> str:
    """Extract video ID from various YouTube URL formats."""
    pattern = r"(?:v=|\/)([0-9A-Za-z_-]{11}).*"
    match = re.search(pattern, url)
    if not match:
        raise ValueError("Invalid YouTube URL")
    return match.group(1)

def get_video_metadata(url: str) -> dict[str, str]:
    ydl_opts = {
        'skip_download': True,
        'extract_flat': True,  # Don't download, just get metadata
        'quiet': True,
        'extractor_args': {'youtube': {'player_client': ['default']}},
    }
    with YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=False)

    metadata = {
        "id": info.get("id"),
        "title": info.get("title"),
        "uploader": info.get("uploader"),
        "upload_date": info.get("upload_date"),
        "duration": info.get("duration"),
        "view_count": info.get("view_count"),
        "like_count": info.get("like_count"),
        "channel_url": info.get("channel_url"),
        "description": info.get("description"),
        "categories": info.get("categories"),
        "tags": info.get("tags"),
        "webpage_url": info.get("webpage_url"),
        "thumbnail": info.get("thumbnail")
    }

    return metadata

def get_youtube_transcript(url: str, languages=None) -> FetchedTranscript:
    if languages is None:
        languages = ['en']
    video_id = get_video_id(url)
    ytt_api = YouTubeTranscriptApi()
    transcript = ytt_api.fetch(video_id, languages=languages)
    return transcript

def serialize_transcript(transcript: FetchedTranscript) -> str:
    return json.dumps(transcript.to_raw_data())

def join_transcript_snippets(transcript: FetchedTranscript) -> str:
    return " ".join(snippet.text for snippet in transcript.snippets)

def save_to_file(content: str, filepath: str | Path):
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

def create_model(config: Config) -> BaseChatModel:
    global __MODEL
    if __MODEL is not None:
        return __MODEL

    from langchain.chat_models import init_chat_model
    model = init_chat_model(
        model=config.model,
        model_provider=config.model_provider,
        **config.model_kwargs
    )
    __MODEL = model
    return model

def get_model() -> BaseChatModel:
    global __MODEL
    if __MODEL is None:
        raise ValueError("Model has not been initialized. Call create_model first.")
    return __MODEL

def format_summary(summary: str, metadata: dict[str, str], video_url: str, generation_date: str) -> str:
    return f"""
# {metadata['title']}
- Generated by ClipDigest - YouTube Video Summarizer on: {generation_date}
- URL: [{video_url}]({video_url})
- By: {metadata['uploader']} on {metadata['upload_date']}
- Duration: {metadata['duration']} seconds

## Description
{metadata['description']}

> The above description is auto-fetched from YouTube video metadata, and not generated by the model.

---

{summary}
    """

def summarize_transcript(model, transcript_text: str, prompt: str = SYSTEM_PROMPT) -> str:
    from langchain_core.prompts import ChatPromptTemplate
    prompt_template = ChatPromptTemplate.from_messages([
        ("system", prompt),
        ("human", "Please summarize the following transcript:\n\n{transcript_text}")
    ])
    final_prompt = prompt_template.invoke({"transcript_text": transcript_text})
    response = model.invoke(final_prompt)
    if isinstance(response, str):
        return response
    return response.text

def handle_video_url(url: str, output_path: Path):
    print("Getting video metadata...")
    metadata =  get_video_metadata(url)
    filename = sanitize_filename(metadata['title'])
    print(f"Fetching transcript for Title: {metadata['title']}...")
    transcript = get_youtube_transcript(url)
    output_path = output_path / f"{filename}_{transcript.video_id}"
    output_path.mkdir(parents=True, exist_ok=True)
    print("Transcript fetched successfully.")
    save_to_file(serialize_transcript(transcript), output_path / "transcript.json")
    print("Serialized transcript saved to transcript.json")
    transcript_text = join_transcript_snippets(transcript)
    save_to_file(transcript_text, output_path / "transcript.txt")
    print("Joined transcript text saved to transcript.txt")
    model = get_model()
    print("Summarizing transcript...")
    summary = summarize_transcript(model, transcript_text)
    generated_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    summary = format_summary(summary, metadata, url, generated_date)
    save_to_file(summary, output_path / f"{filename}.md")
    print(f"Summary saved to {filename}.md")

def main():
    parser = argparse.ArgumentParser(description="ClipDigest - Youtube Video Summarizer")
    parser.add_argument("--url", "-u", type=str, help="URL of the YouTube video to summarize")
    parser.add_argument("-f", "--file", type=str, help="Path to a file containing YouTube video URLs (one per line)")
    parser.add_argument("--custom_prompt", action="store_true", help="Use a custom prompt for summarization")
    parser.add_argument("--custom_prompt_file", "-c", type=str, help="Path to a file containing the custom prompt text")
    parser.add_argument("--output_dir", "-o", type=str, default="outputs", help="Directory to save the output summary")
    parser.add_argument("--model", "-m", type=str, default="gpt-3.5-turbo", help="Language model to use for summarization")
    parser.add_argument("--model_provider", "-p", type=str, default="openai", help="Model provider (e.g., openai, azure, etc.)")
    parser.add_argument("--model_kwargs", type=json.loads, default="{}", help="Additional keyword arguments for the model in JSON format")
    args = parser.parse_args()

    config = Config(
        url=args.url,
        file=args.file,
        use_custom_prompt=args.custom_prompt,
        custom_prompt_file=args.custom_prompt_file if args.custom_prompt else None,
        output_dir=args.output_dir,
        model=args.model,
        model_provider=args.model_provider,
        model_kwargs=args.model_kwargs,
    )
    output_path = Path(config.output_dir)
    if config.file and config.url:
        raise ValueError("Please provide either a URL or a file, not both.")
    if config.file:
        create_model(config)
        print("Processing URLs from file:", config.file)
        with open(config.file, 'r', encoding='utf-8') as f:
            urls = [line.strip() for line in f if line.strip()]
        print("Found", len(urls), "URLs to process.")
        N = len(urls)
        for i, url in enumerate(urls, start=1):
            print(f"{i}/{N} Processing URL: {url}")
            handle_video_url(url, output_path)
            print("---")
    elif config.url:
        create_model(config)
        handle_video_url(config.url, output_path)
    else:
        raise ValueError("Please provide either a URL or a file containing URLs.")





if __name__ == "__main__":
    main()