"""Output formatting and file I/O utilities."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from pathvalidate import sanitize_filename


def format_summary(
    summary: str,
    metadata: dict[str, object],
    video_url: str,
    *,
    generation_date: str | None = None,
) -> str:
    """Wrap a raw LLM summary in a Markdown document with video metadata."""
    from clipdigest.transcript.metadata import format_duration, format_upload_date

    if generation_date is None:
        generation_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    duration_str = format_duration(metadata.get("duration"))
    upload_str = format_upload_date(metadata.get("upload_date"))

    return (
        f"# {metadata.get('title', 'Untitled')}\n\n"
        f"- **Generated by** ClipDigest — YouTube Video Summarizer\n"
        f"- **Generated on:** {generation_date}\n"
        f"- **URL:** [{video_url}]({video_url})\n"
        f"- **Channel:** {metadata.get('uploader', 'unknown')}\n"
        f"- **Published:** {upload_str}\n"
        f"- **Duration:** {duration_str}\n\n"
        f"## Description\n\n"
        f"{metadata.get('description') or '*No description available.*'}\n\n"
        f"> *The description above is fetched directly from YouTube and is not AI-generated.*\n\n"
        f"---\n\n"
        f"{summary.strip()}\n"
    )


def make_output_dir(base: Path, metadata: dict[str, object]) -> Path:
    """Create and return a per-video subdirectory under *base*."""
    title = sanitize_filename(str(metadata.get("title", "video")))
    video_id = str(metadata.get("id", "unknown"))
    folder = base / f"{title}_{video_id}"
    folder.mkdir(parents=True, exist_ok=True)
    return folder


def save_text(content: str, filepath: Path) -> None:
    """Write *content* to *filepath* with UTF-8 encoding."""
    filepath.write_text(content, encoding="utf-8")
